engines:
  rubocop:
    enabled: true
  brakeman:
   	enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
  	enabled: true
    config:
    	languages:
      - ruby
      - javascript
ratings:
  paths:
  - backend/app/**
  - backend/lib/**
exclude_paths:
- spec/**/*
- "**/vendor/**/*"
- design/**/*
- research/**/*
- data/**/*
